import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> 
        <div className="min-h-screen flex bg-gray-100">
          {/* Sidebar */}
          <aside className="w-64 bg-gray-900 text-white flex flex-col py-8 px-4 shadow-lg min-h-screen">
            <div className="mb-10 flex items-center gap-2">
              <span className="text-2xl font-extrabold tracking-wide">SISTEMA</span>
            </div>
            <nav className="flex flex-col gap-4">
              <Link href="/" className="hover:bg-blue-700 rounded px-3 py-2 transition-colors">Início</Link>
              <Link href="/clientes" className="hover:bg-blue-700 rounded px-3 py-2 transition-colors">Clientes</Link>
              <Link href="/produtos" className="hover:bg-blue-700 rounded px-3 py-2 transition-colors">Produtos</Link>
              <Link href="/vendas" className="hover:bg-blue-700 rounded px-3 py-2 transition-colors">Vendas</Link>
            </nav>
            <div className="mt-auto pt-8">
              <button className="w-full bg-red-500 hover:bg-red-600 text-white py-2 rounded transition-colors">Sair</button>
            </div>
          </aside>

          {/* Main content */}
          <div className="flex-1 flex flex-col">
            {/* Topbar */}
            <header className="bg-gray-900 text-white flex items-center justify-between px-8 py-4 shadow">
              <div className="font-bold text-lg tracking-wide">Bem-vindo ao Sistema de Vendas</div>
              <div className="flex items-center gap-3">
                <span className="text-sm">Usuário: <b>Seu Nome</b></span>
                <div className="w-8 h-8 bg-blue-700 rounded-full flex items-center justify-center font-bold">U</div>
              </div>
            </header>

            {/* Conteúdo da página */}
            <main className="flex-1 flex flex-col items-center justify-center p-8">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
